version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - storage:/var/www/html/storage

        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:ak4wyJghO4ioLo9zcPMxZdTRE6obv2EbLEy2r4aKxvQ=
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=erudits
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: erudits
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
    
    soketi:
        image: quay.io/soketi/soketi:1.4-16-debian
        restart: always
        ports:
            - "6001:6001"
            - "9601:9601"

volumes:
  db_data:
  storage:
